// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: service/pb/fantasy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type League struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string       `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LeagueFounder  string       `protobuf:"bytes,2,opt,name=LeagueFounder,proto3" json:"LeagueFounder,omitempty"`
	LeagueName     string       `protobuf:"bytes,3,opt,name=LeagueName,proto3" json:"LeagueName,omitempty"`
	FoundationYear string       `protobuf:"bytes,4,opt,name=FoundationYear,proto3" json:"FoundationYear,omitempty"`
	MaxFranchises  int32        `protobuf:"varint,5,opt,name=MaxFranchises,proto3" json:"MaxFranchises,omitempty"`
	Franchises     []*Franchise `protobuf:"bytes,6,rep,name=Franchises,proto3" json:"Franchises,omitempty"`
}

func (x *League) Reset() {
	*x = League{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *League) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*League) ProtoMessage() {}

func (x *League) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use League.ProtoReflect.Descriptor instead.
func (*League) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{0}
}

func (x *League) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *League) GetLeagueFounder() string {
	if x != nil {
		return x.LeagueFounder
	}
	return ""
}

func (x *League) GetLeagueName() string {
	if x != nil {
		return x.LeagueName
	}
	return ""
}

func (x *League) GetFoundationYear() string {
	if x != nil {
		return x.FoundationYear
	}
	return ""
}

func (x *League) GetMaxFranchises() int32 {
	if x != nil {
		return x.MaxFranchises
	}
	return 0
}

func (x *League) GetFranchises() []*Franchise {
	if x != nil {
		return x.Franchises
	}
	return nil
}

type Franchise struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID             string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FranchisOwner  string `protobuf:"bytes,2,opt,name=FranchisOwner,proto3" json:"FranchisOwner,omitempty"`
	FranchiseName  string `protobuf:"bytes,3,opt,name=FranchiseName,proto3" json:"FranchiseName,omitempty"`
	FoundationYear string `protobuf:"bytes,4,opt,name=FoundationYear,proto3" json:"FoundationYear,omitempty"`
	LeagueID       string `protobuf:"bytes,5,opt,name=LeagueID,proto3" json:"LeagueID,omitempty"`
}

func (x *Franchise) Reset() {
	*x = Franchise{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Franchise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Franchise) ProtoMessage() {}

func (x *Franchise) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Franchise.ProtoReflect.Descriptor instead.
func (*Franchise) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{1}
}

func (x *Franchise) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Franchise) GetFranchisOwner() string {
	if x != nil {
		return x.FranchisOwner
	}
	return ""
}

func (x *Franchise) GetFranchiseName() string {
	if x != nil {
		return x.FranchiseName
	}
	return ""
}

func (x *Franchise) GetFoundationYear() string {
	if x != nil {
		return x.FoundationYear
	}
	return ""
}

func (x *Franchise) GetLeagueID() string {
	if x != nil {
		return x.LeagueID
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LeagueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LeagueName     string `protobuf:"bytes,2,opt,name=leagueName,proto3" json:"leagueName,omitempty"`
	FoundationYear string `protobuf:"bytes,3,opt,name=foundationYear,proto3" json:"foundationYear,omitempty"`
	MaxFranchises  int32  `protobuf:"varint,4,opt,name=maxFranchises,proto3" json:"maxFranchises,omitempty"`
}

func (x *LeagueRequest) Reset() {
	*x = LeagueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeagueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueRequest) ProtoMessage() {}

func (x *LeagueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueRequest.ProtoReflect.Descriptor instead.
func (*LeagueRequest) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{3}
}

func (x *LeagueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeagueRequest) GetLeagueName() string {
	if x != nil {
		return x.LeagueName
	}
	return ""
}

func (x *LeagueRequest) GetFoundationYear() string {
	if x != nil {
		return x.FoundationYear
	}
	return ""
}

func (x *LeagueRequest) GetMaxFranchises() int32 {
	if x != nil {
		return x.MaxFranchises
	}
	return 0
}

type GetLeagueFranchiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetLeagueFranchiseRequest) Reset() {
	*x = GetLeagueFranchiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLeagueFranchiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeagueFranchiseRequest) ProtoMessage() {}

func (x *GetLeagueFranchiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeagueFranchiseRequest.ProtoReflect.Descriptor instead.
func (*GetLeagueFranchiseRequest) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeagueFranchiseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeagueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error    string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LeagueId string `protobuf:"bytes,3,opt,name=leagueId,proto3" json:"leagueId,omitempty"`
}

func (x *LeagueResponse) Reset() {
	*x = LeagueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeagueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueResponse) ProtoMessage() {}

func (x *LeagueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueResponse.ProtoReflect.Descriptor instead.
func (*LeagueResponse) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{5}
}

func (x *LeagueResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LeagueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LeagueResponse) GetLeagueId() string {
	if x != nil {
		return x.LeagueId
	}
	return ""
}

type LeagueFranchisePair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeagueID    string `protobuf:"bytes,1,opt,name=LeagueID,proto3" json:"LeagueID,omitempty"`
	FranchiseID string `protobuf:"bytes,2,opt,name=FranchiseID,proto3" json:"FranchiseID,omitempty"`
}

func (x *LeagueFranchisePair) Reset() {
	*x = LeagueFranchisePair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeagueFranchisePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueFranchisePair) ProtoMessage() {}

func (x *LeagueFranchisePair) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueFranchisePair.ProtoReflect.Descriptor instead.
func (*LeagueFranchisePair) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{6}
}

func (x *LeagueFranchisePair) GetLeagueID() string {
	if x != nil {
		return x.LeagueID
	}
	return ""
}

func (x *LeagueFranchisePair) GetFranchiseID() string {
	if x != nil {
		return x.FranchiseID
	}
	return ""
}

type LeagueFranchisePairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result []*LeagueFranchisePair `protobuf:"bytes,3,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *LeagueFranchisePairResponse) Reset() {
	*x = LeagueFranchisePairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeagueFranchisePairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeagueFranchisePairResponse) ProtoMessage() {}

func (x *LeagueFranchisePairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeagueFranchisePairResponse.ProtoReflect.Descriptor instead.
func (*LeagueFranchisePairResponse) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{7}
}

func (x *LeagueFranchisePairResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *LeagueFranchisePairResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LeagueFranchisePairResponse) GetResult() []*LeagueFranchisePair {
	if x != nil {
		return x.Result
	}
	return nil
}

type FranchiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeagueId       string `protobuf:"bytes,1,opt,name=leagueId,proto3" json:"leagueId,omitempty"`
	FranchiseOwner string `protobuf:"bytes,2,opt,name=franchiseOwner,proto3" json:"franchiseOwner,omitempty"`
	FranchiseName  string `protobuf:"bytes,3,opt,name=franchiseName,proto3" json:"franchiseName,omitempty"`
	FoundationYear string `protobuf:"bytes,4,opt,name=foundationYear,proto3" json:"foundationYear,omitempty"`
}

func (x *FranchiseRequest) Reset() {
	*x = FranchiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FranchiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranchiseRequest) ProtoMessage() {}

func (x *FranchiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranchiseRequest.ProtoReflect.Descriptor instead.
func (*FranchiseRequest) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{8}
}

func (x *FranchiseRequest) GetLeagueId() string {
	if x != nil {
		return x.LeagueId
	}
	return ""
}

func (x *FranchiseRequest) GetFranchiseOwner() string {
	if x != nil {
		return x.FranchiseOwner
	}
	return ""
}

func (x *FranchiseRequest) GetFranchiseName() string {
	if x != nil {
		return x.FranchiseName
	}
	return ""
}

func (x *FranchiseRequest) GetFoundationYear() string {
	if x != nil {
		return x.FoundationYear
	}
	return ""
}

type FranchiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FranchiseId string `protobuf:"bytes,3,opt,name=franchiseId,proto3" json:"franchiseId,omitempty"`
}

func (x *FranchiseResponse) Reset() {
	*x = FranchiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_pb_fantasy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FranchiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FranchiseResponse) ProtoMessage() {}

func (x *FranchiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_pb_fantasy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FranchiseResponse.ProtoReflect.Descriptor instead.
func (*FranchiseResponse) Descriptor() ([]byte, []int) {
	return file_service_pb_fantasy_proto_rawDescGZIP(), []int{9}
}

func (x *FranchiseResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FranchiseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FranchiseResponse) GetFranchiseId() string {
	if x != nil {
		return x.FranchiseId
	}
	return ""
}

var File_service_pb_fantasy_proto protoreflect.FileDescriptor

var file_service_pb_fantasy_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x61, 0x6e,
	0x74, 0x61, 0x73, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x61, 0x6e, 0x74,
	0x61, 0x73, 0x79, 0x22, 0xe0, 0x01, 0x0a, 0x06, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x24,
	0x0a, 0x0d, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x6f, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x24, 0x0a, 0x0d,
	0x4d, 0x61, 0x78, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x4d, 0x61, 0x78, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73,
	0x65, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73, 0x79,
	0x2e, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x0a, 0x46, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x69, 0x73, 0x65, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x69, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x46, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x69, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65,
	0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x49, 0x44, 0x22, 0x55, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x95, 0x01, 0x0a, 0x0d,
	0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x65, 0x61, 0x67, 0x75,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x12, 0x24, 0x0a,
	0x0d, 0x6d, 0x61, 0x78, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69,
	0x73, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x0e, 0x4c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x13, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x46, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x49, 0x44, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x4c, 0x65,
	0x61, 0x67, 0x75, 0x65, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73,
	0x79, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73,
	0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xa4, 0x01,
	0x0a, 0x10, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x66, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73,
	0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x61, 0x6e, 0x63, 0x68,
	0x69, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x66,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x59, 0x65, 0x61, 0x72, 0x22, 0x63, 0x0a, 0x11, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x69, 0x73, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x49, 0x64, 0x32, 0x86, 0x02, 0x0a, 0x0e, 0x46, 0x61,
	0x6e, 0x74, 0x61, 0x73, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x66,
	0x61, 0x6e, 0x74, 0x61, 0x73, 0x79, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73, 0x79, 0x2e, 0x4c,
	0x65, 0x61, 0x67, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x65, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x69, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x22, 0x2e, 0x66, 0x61, 0x6e,
	0x74, 0x61, 0x73, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73, 0x79, 0x2e, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65, 0x46,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x66, 0x61, 0x6e, 0x74,
	0x61, 0x73, 0x79, 0x2e, 0x46, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x66, 0x61, 0x6e, 0x74, 0x61, 0x73, 0x79, 0x2e, 0x46,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_pb_fantasy_proto_rawDescOnce sync.Once
	file_service_pb_fantasy_proto_rawDescData = file_service_pb_fantasy_proto_rawDesc
)

func file_service_pb_fantasy_proto_rawDescGZIP() []byte {
	file_service_pb_fantasy_proto_rawDescOnce.Do(func() {
		file_service_pb_fantasy_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_pb_fantasy_proto_rawDescData)
	})
	return file_service_pb_fantasy_proto_rawDescData
}

var file_service_pb_fantasy_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_pb_fantasy_proto_goTypes = []interface{}{
	(*League)(nil),                      // 0: fantasy.League
	(*Franchise)(nil),                   // 1: fantasy.Franchise
	(*QueryResponse)(nil),               // 2: fantasy.QueryResponse
	(*LeagueRequest)(nil),               // 3: fantasy.LeagueRequest
	(*GetLeagueFranchiseRequest)(nil),   // 4: fantasy.GetLeagueFranchiseRequest
	(*LeagueResponse)(nil),              // 5: fantasy.LeagueResponse
	(*LeagueFranchisePair)(nil),         // 6: fantasy.LeagueFranchisePair
	(*LeagueFranchisePairResponse)(nil), // 7: fantasy.LeagueFranchisePairResponse
	(*FranchiseRequest)(nil),            // 8: fantasy.FranchiseRequest
	(*FranchiseResponse)(nil),           // 9: fantasy.FranchiseResponse
}
var file_service_pb_fantasy_proto_depIdxs = []int32{
	1, // 0: fantasy.League.Franchises:type_name -> fantasy.Franchise
	6, // 1: fantasy.LeagueFranchisePairResponse.result:type_name -> fantasy.LeagueFranchisePair
	3, // 2: fantasy.FantasyService.CreateLeague:input_type -> fantasy.LeagueRequest
	4, // 3: fantasy.FantasyService.GetLeagueFranchisePairs:input_type -> fantasy.GetLeagueFranchiseRequest
	8, // 4: fantasy.FantasyService.CreateFranchise:input_type -> fantasy.FranchiseRequest
	5, // 5: fantasy.FantasyService.CreateLeague:output_type -> fantasy.LeagueResponse
	7, // 6: fantasy.FantasyService.GetLeagueFranchisePairs:output_type -> fantasy.LeagueFranchisePairResponse
	9, // 7: fantasy.FantasyService.CreateFranchise:output_type -> fantasy.FranchiseResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_pb_fantasy_proto_init() }
func file_service_pb_fantasy_proto_init() {
	if File_service_pb_fantasy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_pb_fantasy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*League); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Franchise); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeagueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLeagueFranchiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeagueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeagueFranchisePair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeagueFranchisePairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FranchiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_pb_fantasy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FranchiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_pb_fantasy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_pb_fantasy_proto_goTypes,
		DependencyIndexes: file_service_pb_fantasy_proto_depIdxs,
		MessageInfos:      file_service_pb_fantasy_proto_msgTypes,
	}.Build()
	File_service_pb_fantasy_proto = out.File
	file_service_pb_fantasy_proto_rawDesc = nil
	file_service_pb_fantasy_proto_goTypes = nil
	file_service_pb_fantasy_proto_depIdxs = nil
}
